modLoader="javafml" #mandatory
loaderVersion="[39,]" #mandatory
license="MIT" #mandatory
credits="LK1905" #optional
[[mods]] #mandatory
modId="gielinorcraft" #mandatory
version="0.0.8" #mandatory
displayName="Gielinorcraft" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/gielinorcraft" #optional
description='''
A Runescape themed Minecraft Mod
'''