modLoader="javafml" #mandatory
loaderVersion="[35.1]" #mandatory
license="MIT" #mandatory
credits="LK1905" #optional
[[mods]] #mandatory
modId="gielinorcraft" #mandatory
version="0.0.0" #mandatory
displayName="Gielinorcraft" #mandatory
description='''
A Runescape themed Minecraft Mod
'''